"""PIN Code lookup routes"""
from fastapi import APIRouter, HTTPException, Query
from typing import Optional

router = APIRouter()

# Basic PIN to City/State mapping for common Indian PIN codes
# This is a simplified mapping - in production, you'd use a proper API or database
PIN_CODE_MAPPING = {
    # Maharashtra
    "400001": {"city": "Mumbai", "state": "Maharashtra"},
    "400002": {"city": "Mumbai", "state": "Maharashtra"},
    "400003": {"city": "Mumbai", "state": "Maharashtra"},
    "400004": {"city": "Mumbai", "state": "Maharashtra"},
    "400005": {"city": "Mumbai", "state": "Maharashtra"},
    "400006": {"city": "Mumbai", "state": "Maharashtra"},
    "400007": {"city": "Mumbai", "state": "Maharashtra"},
    "400008": {"city": "Mumbai", "state": "Maharashtra"},
    "400009": {"city": "Mumbai", "state": "Maharashtra"},
    "400010": {"city": "Mumbai", "state": "Maharashtra"},
    "400011": {"city": "Mumbai", "state": "Maharashtra"},
    "400012": {"city": "Mumbai", "state": "Maharashtra"},
    "400013": {"city": "Mumbai", "state": "Maharashtra"},
    "400014": {"city": "Mumbai", "state": "Maharashtra"},
    "400015": {"city": "Mumbai", "state": "Maharashtra"},
    "400016": {"city": "Mumbai", "state": "Maharashtra"},
    "400017": {"city": "Mumbai", "state": "Maharashtra"},
    "400018": {"city": "Mumbai", "state": "Maharashtra"},
    "400019": {"city": "Mumbai", "state": "Maharashtra"},
    "400020": {"city": "Mumbai", "state": "Maharashtra"},
    "400021": {"city": "Mumbai", "state": "Maharashtra"},
    "400022": {"city": "Mumbai", "state": "Maharashtra"},
    "400023": {"city": "Mumbai", "state": "Maharashtra"},
    "400024": {"city": "Mumbai", "state": "Maharashtra"},
    "400025": {"city": "Mumbai", "state": "Maharashtra"},
    "400026": {"city": "Mumbai", "state": "Maharashtra"},
    "400027": {"city": "Mumbai", "state": "Maharashtra"},
    "400028": {"city": "Mumbai", "state": "Maharashtra"},
    "400029": {"city": "Mumbai", "state": "Maharashtra"},
    "400030": {"city": "Mumbai", "state": "Maharashtra"},
    "400031": {"city": "Mumbai", "state": "Maharashtra"},
    "400032": {"city": "Mumbai", "state": "Maharashtra"},
    "400033": {"city": "Mumbai", "state": "Maharashtra"},
    "400034": {"city": "Mumbai", "state": "Maharashtra"},
    "400035": {"city": "Mumbai", "state": "Maharashtra"},
    "400036": {"city": "Mumbai", "state": "Maharashtra"},
    "400037": {"city": "Mumbai", "state": "Maharashtra"},
    "400038": {"city": "Mumbai", "state": "Maharashtra"},
    "400039": {"city": "Mumbai", "state": "Maharashtra"},
    "400040": {"city": "Mumbai", "state": "Maharashtra"},
    "400041": {"city": "Mumbai", "state": "Maharashtra"},
    "400042": {"city": "Mumbai", "state": "Maharashtra"},
    "400043": {"city": "Mumbai", "state": "Maharashtra"},
    "400044": {"city": "Mumbai", "state": "Maharashtra"},
    "400045": {"city": "Mumbai", "state": "Maharashtra"},
    "400046": {"city": "Mumbai", "state": "Maharashtra"},
    "400047": {"city": "Mumbai", "state": "Maharashtra"},
    "400048": {"city": "Mumbai", "state": "Maharashtra"},
    "400049": {"city": "Mumbai", "state": "Maharashtra"},
    "400050": {"city": "Mumbai", "state": "Maharashtra"},
    "400051": {"city": "Mumbai", "state": "Maharashtra"},
    "400052": {"city": "Mumbai", "state": "Maharashtra"},
    "400053": {"city": "Mumbai", "state": "Maharashtra"},
    "400054": {"city": "Mumbai", "state": "Maharashtra"},
    "400055": {"city": "Mumbai", "state": "Maharashtra"},
    "400056": {"city": "Mumbai", "state": "Maharashtra"},
    "400057": {"city": "Mumbai", "state": "Maharashtra"},
    "400058": {"city": "Mumbai", "state": "Maharashtra"},
    "400059": {"city": "Mumbai", "state": "Maharashtra"},
    "400060": {"city": "Mumbai", "state": "Maharashtra"},
    "400061": {"city": "Mumbai", "state": "Maharashtra"},
    "400062": {"city": "Mumbai", "state": "Maharashtra"},
    "400063": {"city": "Mumbai", "state": "Maharashtra"},
    "400064": {"city": "Mumbai", "state": "Maharashtra"},
    "400065": {"city": "Mumbai", "state": "Maharashtra"},
    "400066": {"city": "Mumbai", "state": "Maharashtra"},
    "400067": {"city": "Mumbai", "state": "Maharashtra"},
    "400068": {"city": "Mumbai", "state": "Maharashtra"},
    "400069": {"city": "Mumbai", "state": "Maharashtra"},
    "400070": {"city": "Mumbai", "state": "Maharashtra"},
    "400071": {"city": "Mumbai", "state": "Maharashtra"},
    "400072": {"city": "Mumbai", "state": "Maharashtra"},
    "400073": {"city": "Mumbai", "state": "Maharashtra"},
    "400074": {"city": "Mumbai", "state": "Maharashtra"},
    "400075": {"city": "Mumbai", "state": "Maharashtra"},
    "400076": {"city": "Mumbai", "state": "Maharashtra"},
    "400077": {"city": "Mumbai", "state": "Maharashtra"},
    "400078": {"city": "Mumbai", "state": "Maharashtra"},
    "400079": {"city": "Mumbai", "state": "Maharashtra"},
    "400080": {"city": "Mumbai", "state": "Maharashtra"},
    "400081": {"city": "Mumbai", "state": "Maharashtra"},
    "400082": {"city": "Mumbai", "state": "Maharashtra"},
    "400083": {"city": "Mumbai", "state": "Maharashtra"},
    "400084": {"city": "Mumbai", "state": "Maharashtra"},
    "400085": {"city": "Mumbai", "state": "Maharashtra"},
    "400086": {"city": "Mumbai", "state": "Maharashtra"},
    "400087": {"city": "Mumbai", "state": "Maharashtra"},
    "400088": {"city": "Mumbai", "state": "Maharashtra"},
    "400089": {"city": "Mumbai", "state": "Maharashtra"},
    "400090": {"city": "Mumbai", "state": "Maharashtra"},
    "400091": {"city": "Mumbai", "state": "Maharashtra"},
    "400092": {"city": "Mumbai", "state": "Maharashtra"},
    "400093": {"city": "Mumbai", "state": "Maharashtra"},
    "400094": {"city": "Mumbai", "state": "Maharashtra"},
    "400095": {"city": "Mumbai", "state": "Maharashtra"},
    "400096": {"city": "Mumbai", "state": "Maharashtra"},
    "400097": {"city": "Mumbai", "state": "Maharashtra"},
    "400098": {"city": "Mumbai", "state": "Maharashtra"},
    "400099": {"city": "Mumbai", "state": "Maharashtra"},
    "400100": {"city": "Mumbai", "state": "Maharashtra"},
    "400101": {"city": "Mumbai", "state": "Maharashtra"},
    "400102": {"city": "Mumbai", "state": "Maharashtra"},
    "400103": {"city": "Mumbai", "state": "Maharashtra"},
    "400104": {"city": "Mumbai", "state": "Maharashtra"},
    "400105": {"city": "Mumbai", "state": "Maharashtra"},
    "400106": {"city": "Mumbai", "state": "Maharashtra"},
    "400107": {"city": "Mumbai", "state": "Maharashtra"},
    "400601": {"city": "Thane", "state": "Maharashtra"},
    "400602": {"city": "Thane", "state": "Maharashtra"},
    "400603": {"city": "Thane", "state": "Maharashtra"},
    "400604": {"city": "Thane", "state": "Maharashtra"},
    "400605": {"city": "Thane", "state": "Maharashtra"},
    "400606": {"city": "Thane", "state": "Maharashtra"},
    "400607": {"city": "Thane", "state": "Maharashtra"},
    "400608": {"city": "Thane", "state": "Maharashtra"},
    "400609": {"city": "Thane", "state": "Maharashtra"},
    "400610": {"city": "Thane", "state": "Maharashtra"},
    "400701": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400702": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400703": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400704": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400705": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400706": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400707": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400708": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400709": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "400710": {"city": "Navi Mumbai", "state": "Maharashtra"},
    "411001": {"city": "Pune", "state": "Maharashtra"},
    "411002": {"city": "Pune", "state": "Maharashtra"},
    "411003": {"city": "Pune", "state": "Maharashtra"},
    "411004": {"city": "Pune", "state": "Maharashtra"},
    "411005": {"city": "Pune", "state": "Maharashtra"},
    "411006": {"city": "Pune", "state": "Maharashtra"},
    "411007": {"city": "Pune", "state": "Maharashtra"},
    "411008": {"city": "Pune", "state": "Maharashtra"},
    "411009": {"city": "Pune", "state": "Maharashtra"},
    "411010": {"city": "Pune", "state": "Maharashtra"},
    "411011": {"city": "Pune", "state": "Maharashtra"},
    "411012": {"city": "Pune", "state": "Maharashtra"},
    "411013": {"city": "Pune", "state": "Maharashtra"},
    "411014": {"city": "Pune", "state": "Maharashtra"},
    "411015": {"city": "Pune", "state": "Maharashtra"},
    "411016": {"city": "Pune", "state": "Maharashtra"},
    "411017": {"city": "Pune", "state": "Maharashtra"},
    "411018": {"city": "Pune", "state": "Maharashtra"},
    "411019": {"city": "Pune", "state": "Maharashtra"},
    "411020": {"city": "Pune", "state": "Maharashtra"},
    "411021": {"city": "Pune", "state": "Maharashtra"},
    "411022": {"city": "Pune", "state": "Maharashtra"},
    "411023": {"city": "Pune", "state": "Maharashtra"},
    "411024": {"city": "Pune", "state": "Maharashtra"},
    "411025": {"city": "Pune", "state": "Maharashtra"},
    "411026": {"city": "Pune", "state": "Maharashtra"},
    "411027": {"city": "Pune", "state": "Maharashtra"},
    "411028": {"city": "Pune", "state": "Maharashtra"},
    "411029": {"city": "Pune", "state": "Maharashtra"},
    "411030": {"city": "Pune", "state": "Maharashtra"},
    "411031": {"city": "Pune", "state": "Maharashtra"},
    "411032": {"city": "Pune", "state": "Maharashtra"},
    "411033": {"city": "Pune", "state": "Maharashtra"},
    "411034": {"city": "Pune", "state": "Maharashtra"},
    "411035": {"city": "Pune", "state": "Maharashtra"},
    "411036": {"city": "Pune", "state": "Maharashtra"},
    "411037": {"city": "Pune", "state": "Maharashtra"},
    "411038": {"city": "Pune", "state": "Maharashtra"},
    "411039": {"city": "Pune", "state": "Maharashtra"},
    "411040": {"city": "Pune", "state": "Maharashtra"},
    "411041": {"city": "Pune", "state": "Maharashtra"},
    "411042": {"city": "Pune", "state": "Maharashtra"},
    "411043": {"city": "Pune", "state": "Maharashtra"},
    "411044": {"city": "Pune", "state": "Maharashtra"},
    "411045": {"city": "Pune", "state": "Maharashtra"},
    "411046": {"city": "Pune", "state": "Maharashtra"},
    "411047": {"city": "Pune", "state": "Maharashtra"},
    "411048": {"city": "Pune", "state": "Maharashtra"},
    "411049": {"city": "Pune", "state": "Maharashtra"},
    "411050": {"city": "Pune", "state": "Maharashtra"},
    "411051": {"city": "Pune", "state": "Maharashtra"},
    "411052": {"city": "Pune", "state": "Maharashtra"},
    "411053": {"city": "Pune", "state": "Maharashtra"},
    "411054": {"city": "Pune", "state": "Maharashtra"},
    "411055": {"city": "Pune", "state": "Maharashtra"},
    "411056": {"city": "Pune", "state": "Maharashtra"},
    "411057": {"city": "Pune", "state": "Maharashtra"},
    "411058": {"city": "Pune", "state": "Maharashtra"},
    "411059": {"city": "Pune", "state": "Maharashtra"},
    "411060": {"city": "Pune", "state": "Maharashtra"},
    "411061": {"city": "Pune", "state": "Maharashtra"},
    "411062": {"city": "Pune", "state": "Maharashtra"},
    "411063": {"city": "Pune", "state": "Maharashtra"},
    "411064": {"city": "Pune", "state": "Maharashtra"},
    "411065": {"city": "Pune", "state": "Maharashtra"},
    "411066": {"city": "Pune", "state": "Maharashtra"},
    "411067": {"city": "Pune", "state": "Maharashtra"},
    "411068": {"city": "Pune", "state": "Maharashtra"},
    "411069": {"city": "Pune", "state": "Maharashtra"},
    "411070": {"city": "Pune", "state": "Maharashtra"},
    "411071": {"city": "Pune", "state": "Maharashtra"},
    "411072": {"city": "Pune", "state": "Maharashtra"},
    "411073": {"city": "Pune", "state": "Maharashtra"},
    "411074": {"city": "Pune", "state": "Maharashtra"},
    "411075": {"city": "Pune", "state": "Maharashtra"},
    "411076": {"city": "Pune", "state": "Maharashtra"},
    "411077": {"city": "Pune", "state": "Maharashtra"},
    "411078": {"city": "Pune", "state": "Maharashtra"},
    "411079": {"city": "Pune", "state": "Maharashtra"},
    "411080": {"city": "Pune", "state": "Maharashtra"},
    "411081": {"city": "Pune", "state": "Maharashtra"},
    "411082": {"city": "Pune", "state": "Maharashtra"},
    "411083": {"city": "Pune", "state": "Maharashtra"},
    "411084": {"city": "Pune", "state": "Maharashtra"},
    "411085": {"city": "Pune", "state": "Maharashtra"},
    "411086": {"city": "Pune", "state": "Maharashtra"},
    "411087": {"city": "Pune", "state": "Maharashtra"},
    "411088": {"city": "Pune", "state": "Maharashtra"},
    "411089": {"city": "Pune", "state": "Maharashtra"},
    "411090": {"city": "Pune", "state": "Maharashtra"},
    "411091": {"city": "Pune", "state": "Maharashtra"},
    "411092": {"city": "Pune", "state": "Maharashtra"},
    "411093": {"city": "Pune", "state": "Maharashtra"},
    "411094": {"city": "Pune", "state": "Maharashtra"},
    "411095": {"city": "Pune", "state": "Maharashtra"},
    "411096": {"city": "Pune", "state": "Maharashtra"},
    "411097": {"city": "Pune", "state": "Maharashtra"},
    "411098": {"city": "Pune", "state": "Maharashtra"},
    "411099": {"city": "Pune", "state": "Maharashtra"},
    "411100": {"city": "Pune", "state": "Maharashtra"},
    # Karnataka
    "560001": {"city": "Bangalore", "state": "Karnataka"},
    "560002": {"city": "Bangalore", "state": "Karnataka"},
    "560003": {"city": "Bangalore", "state": "Karnataka"},
    "560004": {"city": "Bangalore", "state": "Karnataka"},
    "560005": {"city": "Bangalore", "state": "Karnataka"},
    "560006": {"city": "Bangalore", "state": "Karnataka"},
    "560007": {"city": "Bangalore", "state": "Karnataka"},
    "560008": {"city": "Bangalore", "state": "Karnataka"},
    "560009": {"city": "Bangalore", "state": "Karnataka"},
    "560010": {"city": "Bangalore", "state": "Karnataka"},
    "560011": {"city": "Bangalore", "state": "Karnataka"},
    "560012": {"city": "Bangalore", "state": "Karnataka"},
    "560013": {"city": "Bangalore", "state": "Karnataka"},
    "560014": {"city": "Bangalore", "state": "Karnataka"},
    "560015": {"city": "Bangalore", "state": "Karnataka"},
    "560016": {"city": "Bangalore", "state": "Karnataka"},
    "560017": {"city": "Bangalore", "state": "Karnataka"},
    "560018": {"city": "Bangalore", "state": "Karnataka"},
    "560019": {"city": "Bangalore", "state": "Karnataka"},
    "560020": {"city": "Bangalore", "state": "Karnataka"},
    "560021": {"city": "Bangalore", "state": "Karnataka"},
    "560022": {"city": "Bangalore", "state": "Karnataka"},
    "560023": {"city": "Bangalore", "state": "Karnataka"},
    "560024": {"city": "Bangalore", "state": "Karnataka"},
    "560025": {"city": "Bangalore", "state": "Karnataka"},
    "560026": {"city": "Bangalore", "state": "Karnataka"},
    "560027": {"city": "Bangalore", "state": "Karnataka"},
    "560028": {"city": "Bangalore", "state": "Karnataka"},
    "560029": {"city": "Bangalore", "state": "Karnataka"},
    "560030": {"city": "Bangalore", "state": "Karnataka"},
    "560031": {"city": "Bangalore", "state": "Karnataka"},
    "560032": {"city": "Bangalore", "state": "Karnataka"},
    "560033": {"city": "Bangalore", "state": "Karnataka"},
    "560034": {"city": "Bangalore", "state": "Karnataka"},
    "560035": {"city": "Bangalore", "state": "Karnataka"},
    "560036": {"city": "Bangalore", "state": "Karnataka"},
    "560037": {"city": "Bangalore", "state": "Karnataka"},
    "560038": {"city": "Bangalore", "state": "Karnataka"},
    "560039": {"city": "Bangalore", "state": "Karnataka"},
    "560040": {"city": "Bangalore", "state": "Karnataka"},
    "560041": {"city": "Bangalore", "state": "Karnataka"},
    "560042": {"city": "Bangalore", "state": "Karnataka"},
    "560043": {"city": "Bangalore", "state": "Karnataka"},
    "560044": {"city": "Bangalore", "state": "Karnataka"},
    "560045": {"city": "Bangalore", "state": "Karnataka"},
    "560046": {"city": "Bangalore", "state": "Karnataka"},
    "560047": {"city": "Bangalore", "state": "Karnataka"},
    "560048": {"city": "Bangalore", "state": "Karnataka"},
    "560049": {"city": "Bangalore", "state": "Karnataka"},
    "560050": {"city": "Bangalore", "state": "Karnataka"},
    "560051": {"city": "Bangalore", "state": "Karnataka"},
    "560052": {"city": "Bangalore", "state": "Karnataka"},
    "560053": {"city": "Bangalore", "state": "Karnataka"},
    "560054": {"city": "Bangalore", "state": "Karnataka"},
    "560055": {"city": "Bangalore", "state": "Karnataka"},
    "560056": {"city": "Bangalore", "state": "Karnataka"},
    "560057": {"city": "Bangalore", "state": "Karnataka"},
    "560058": {"city": "Bangalore", "state": "Karnataka"},
    "560059": {"city": "Bangalore", "state": "Karnataka"},
    "560060": {"city": "Bangalore", "state": "Karnataka"},
    "560061": {"city": "Bangalore", "state": "Karnataka"},
    "560062": {"city": "Bangalore", "state": "Karnataka"},
    "560063": {"city": "Bangalore", "state": "Karnataka"},
    "560064": {"city": "Bangalore", "state": "Karnataka"},
    "560065": {"city": "Bangalore", "state": "Karnataka"},
    "560066": {"city": "Bangalore", "state": "Karnataka"},
    "560067": {"city": "Bangalore", "state": "Karnataka"},
    "560068": {"city": "Bangalore", "state": "Karnataka"},
    "560069": {"city": "Bangalore", "state": "Karnataka"},
    "560070": {"city": "Bangalore", "state": "Karnataka"},
    "560071": {"city": "Bangalore", "state": "Karnataka"},
    "560072": {"city": "Bangalore", "state": "Karnataka"},
    "560073": {"city": "Bangalore", "state": "Karnataka"},
    "560074": {"city": "Bangalore", "state": "Karnataka"},
    "560075": {"city": "Bangalore", "state": "Karnataka"},
    "560076": {"city": "Bangalore", "state": "Karnataka"},
    "560077": {"city": "Bangalore", "state": "Karnataka"},
    "560078": {"city": "Bangalore", "state": "Karnataka"},
    "560079": {"city": "Bangalore", "state": "Karnataka"},
    "560080": {"city": "Bangalore", "state": "Karnataka"},
    "560081": {"city": "Bangalore", "state": "Karnataka"},
    "560082": {"city": "Bangalore", "state": "Karnataka"},
    "560083": {"city": "Bangalore", "state": "Karnataka"},
    "560084": {"city": "Bangalore", "state": "Karnataka"},
    "560085": {"city": "Bangalore", "state": "Karnataka"},
    "560086": {"city": "Bangalore", "state": "Karnataka"},
    "560087": {"city": "Bangalore", "state": "Karnataka"},
    "560088": {"city": "Bangalore", "state": "Karnataka"},
    "560089": {"city": "Bangalore", "state": "Karnataka"},
    "560090": {"city": "Bangalore", "state": "Karnataka"},
    "560091": {"city": "Bangalore", "state": "Karnataka"},
    "560092": {"city": "Bangalore", "state": "Karnataka"},
    "560093": {"city": "Bangalore", "state": "Karnataka"},
    "560094": {"city": "Bangalore", "state": "Karnataka"},
    "560095": {"city": "Bangalore", "state": "Karnataka"},
    "560096": {"city": "Bangalore", "state": "Karnataka"},
    "560097": {"city": "Bangalore", "state": "Karnataka"},
    "560098": {"city": "Bangalore", "state": "Karnataka"},
    "560099": {"city": "Bangalore", "state": "Karnataka"},
    "560100": {"city": "Bangalore", "state": "Karnataka"},
    # Delhi
    "110001": {"city": "New Delhi", "state": "Delhi"},
    "110002": {"city": "New Delhi", "state": "Delhi"},
    "110003": {"city": "New Delhi", "state": "Delhi"},
    "110004": {"city": "New Delhi", "state": "Delhi"},
    "110005": {"city": "New Delhi", "state": "Delhi"},
    "110006": {"city": "New Delhi", "state": "Delhi"},
    "110007": {"city": "New Delhi", "state": "Delhi"},
    "110008": {"city": "New Delhi", "state": "Delhi"},
    "110009": {"city": "New Delhi", "state": "Delhi"},
    "110010": {"city": "New Delhi", "state": "Delhi"},
    "110011": {"city": "New Delhi", "state": "Delhi"},
    "110012": {"city": "New Delhi", "state": "Delhi"},
    "110013": {"city": "New Delhi", "state": "Delhi"},
    "110014": {"city": "New Delhi", "state": "Delhi"},
    "110015": {"city": "New Delhi", "state": "Delhi"},
    "110016": {"city": "New Delhi", "state": "Delhi"},
    "110017": {"city": "New Delhi", "state": "Delhi"},
    "110018": {"city": "New Delhi", "state": "Delhi"},
    "110019": {"city": "New Delhi", "state": "Delhi"},
    "110020": {"city": "New Delhi", "state": "Delhi"},
    "110021": {"city": "New Delhi", "state": "Delhi"},
    "110022": {"city": "New Delhi", "state": "Delhi"},
    "110023": {"city": "New Delhi", "state": "Delhi"},
    "110024": {"city": "New Delhi", "state": "Delhi"},
    "110025": {"city": "New Delhi", "state": "Delhi"},
    "110026": {"city": "New Delhi", "state": "Delhi"},
    "110027": {"city": "New Delhi", "state": "Delhi"},
    "110028": {"city": "New Delhi", "state": "Delhi"},
    "110029": {"city": "New Delhi", "state": "Delhi"},
    "110030": {"city": "New Delhi", "state": "Delhi"},
    "110031": {"city": "New Delhi", "state": "Delhi"},
    "110032": {"city": "New Delhi", "state": "Delhi"},
    "110033": {"city": "New Delhi", "state": "Delhi"},
    "110034": {"city": "New Delhi", "state": "Delhi"},
    "110035": {"city": "New Delhi", "state": "Delhi"},
    "110036": {"city": "New Delhi", "state": "Delhi"},
    "110037": {"city": "New Delhi", "state": "Delhi"},
    "110038": {"city": "New Delhi", "state": "Delhi"},
    "110039": {"city": "New Delhi", "state": "Delhi"},
    "110040": {"city": "New Delhi", "state": "Delhi"},
    "110041": {"city": "New Delhi", "state": "Delhi"},
    "110042": {"city": "New Delhi", "state": "Delhi"},
    "110043": {"city": "New Delhi", "state": "Delhi"},
    "110044": {"city": "New Delhi", "state": "Delhi"},
    "110045": {"city": "New Delhi", "state": "Delhi"},
    "110046": {"city": "New Delhi", "state": "Delhi"},
    "110047": {"city": "New Delhi", "state": "Delhi"},
    "110048": {"city": "New Delhi", "state": "Delhi"},
    "110049": {"city": "New Delhi", "state": "Delhi"},
    "110050": {"city": "New Delhi", "state": "Delhi"},
    "110051": {"city": "New Delhi", "state": "Delhi"},
    "110052": {"city": "New Delhi", "state": "Delhi"},
    "110053": {"city": "New Delhi", "state": "Delhi"},
    "110054": {"city": "New Delhi", "state": "Delhi"},
    "110055": {"city": "New Delhi", "state": "Delhi"},
    "110056": {"city": "New Delhi", "state": "Delhi"},
    "110057": {"city": "New Delhi", "state": "Delhi"},
    "110058": {"city": "New Delhi", "state": "Delhi"},
    "110059": {"city": "New Delhi", "state": "Delhi"},
    "110060": {"city": "New Delhi", "state": "Delhi"},
    "110061": {"city": "New Delhi", "state": "Delhi"},
    "110062": {"city": "New Delhi", "state": "Delhi"},
    "110063": {"city": "New Delhi", "state": "Delhi"},
    "110064": {"city": "New Delhi", "state": "Delhi"},
    "110065": {"city": "New Delhi", "state": "Delhi"},
    "110066": {"city": "New Delhi", "state": "Delhi"},
    "110067": {"city": "New Delhi", "state": "Delhi"},
    "110068": {"city": "New Delhi", "state": "Delhi"},
    "110069": {"city": "New Delhi", "state": "Delhi"},
    "110070": {"city": "New Delhi", "state": "Delhi"},
    "110071": {"city": "New Delhi", "state": "Delhi"},
    "110072": {"city": "New Delhi", "state": "Delhi"},
    "110073": {"city": "New Delhi", "state": "Delhi"},
    "110074": {"city": "New Delhi", "state": "Delhi"},
    "110075": {"city": "New Delhi", "state": "Delhi"},
    "110076": {"city": "New Delhi", "state": "Delhi"},
    "110077": {"city": "New Delhi", "state": "Delhi"},
    "110078": {"city": "New Delhi", "state": "Delhi"},
    "110079": {"city": "New Delhi", "state": "Delhi"},
    "110080": {"city": "New Delhi", "state": "Delhi"},
    "110081": {"city": "New Delhi", "state": "Delhi"},
    "110082": {"city": "New Delhi", "state": "Delhi"},
    "110083": {"city": "New Delhi", "state": "Delhi"},
    "110084": {"city": "New Delhi", "state": "Delhi"},
    "110085": {"city": "New Delhi", "state": "Delhi"},
    "110086": {"city": "New Delhi", "state": "Delhi"},
    "110087": {"city": "New Delhi", "state": "Delhi"},
    "110088": {"city": "New Delhi", "state": "Delhi"},
    "110089": {"city": "New Delhi", "state": "Delhi"},
    "110090": {"city": "New Delhi", "state": "Delhi"},
    "110091": {"city": "New Delhi", "state": "Delhi"},
    "110092": {"city": "New Delhi", "state": "Delhi"},
    "110093": {"city": "New Delhi", "state": "Delhi"},
    "110094": {"city": "New Delhi", "state": "Delhi"},
    "110095": {"city": "New Delhi", "state": "Delhi"},
    "110096": {"city": "New Delhi", "state": "Delhi"},
    "110097": {"city": "New Delhi", "state": "Delhi"},
    "110098": {"city": "New Delhi", "state": "Delhi"},
    "110099": {"city": "New Delhi", "state": "Delhi"},
    "110100": {"city": "New Delhi", "state": "Delhi"},
}

# Indian states list
INDIAN_STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
    "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
    "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
    "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
    "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
    "Uttar Pradesh", "Uttarakhand", "West Bengal",
    "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
]


@router.get("/lookup")
async def lookup_pincode(
    pincode: str = Query(..., min_length=6, max_length=6, description="6-digit PIN code")
):
    """
    Lookup city and state from PIN code
    Returns city and state if found, otherwise returns None
    """
    # Clean the PIN code (remove spaces, ensure 6 digits)
    pincode_clean = pincode.strip().replace(" ", "")
    
    if len(pincode_clean) != 6 or not pincode_clean.isdigit():
        raise HTTPException(
            status_code=400,
            detail="PIN code must be exactly 6 digits"
        )
    
    # Lookup in mapping
    result = PIN_CODE_MAPPING.get(pincode_clean)
    
    if result:
        return {
            "pincode": pincode_clean,
            "city": result["city"],
            "state": result["state"],
            "found": True
        }
    else:
        # If not found, try to infer from first digit (rough approximation)
        first_digit = pincode_clean[0]
        state_hints = {
            "1": "Delhi/NCR",
            "2": "Uttar Pradesh/Uttarakhand",
            "3": "Rajasthan/Gujarat",
            "4": "Maharashtra/Goa",
            "5": "Andhra Pradesh/Telangana",
            "6": "Karnataka",
            "7": "Kerala/Tamil Nadu",
            "8": "West Bengal/Orissa",
            "9": "Punjab/Haryana/Himachal Pradesh"
        }
        
        return {
            "pincode": pincode_clean,
            "city": None,
            "state": state_hints.get(first_digit, "Unknown"),
            "found": False,
            "message": "PIN code not found in database. Please enter city and state manually."
        }


@router.get("/states")
async def get_states():
    """Get list of all Indian states"""
    return {
        "states": INDIAN_STATES
    }



